package com.example.rs_link.data.repository

import com.example.rs_link.data.model.User
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore
import kotlinx.coroutines.delay
import kotlinx.coroutines.tasks.await
import javax.inject.Inject

class UserRepositoryImpl @Inject constructor(
    private val auth: FirebaseAuth,
    private val firestore: FirebaseFirestore
) : UserRepository {

    override suspend fun login(email: String, password: String) {
        // Firebase Auth Login
        auth.signInWithEmailAndPassword(email, password).await()
    }
    override suspend fun registerUser(user: User, password: String) {
        // 1. Create Auth User (Email/Password)
        val authResult = auth.createUserWithEmailAndPassword(user.email, password).await()
        val firebaseUser = authResult.user ?: throw Exception("User creation failed")

        // 2. Create the User object with the new Firebase ID
        // (Copy the ID generated by Auth into your User model)
        val newUserWithId = user.copy(id = firebaseUser.uid)

        // 3. Save the Profile Data to Firestore
        firestore.collection("users")
            .document(firebaseUser.uid) // Use the Auth ID as the Document ID
            .set(newUserWithId)
            .await()
    }
    override fun logout() {
        auth.signOut()
    }

    override fun isUserLoggedIn(): Boolean {
        return auth.currentUser != null
    }

    override fun getCurrentUserId(): String? {
        return auth.currentUser?.uid
    }
    override suspend fun getUserProfile(userId: String): User? {
        // Fetch the document from Firestore and convert it to your User object
        return try {
            // Go to "users" collection -> find document with userId -> fetch it
            val snapshot = firestore.collection("users")
                .document(userId)
                .get()
                .await() // Suspends until data is ready

            // Convert the JSON document into your Kotlin 'User' object
            snapshot.toObject(User::class.java)
        } catch (e: Exception) {
            e.printStackTrace()
            null // Return null if network fails
        }
    }

    override suspend fun updateUserProfile(user: User) {
        // Ensure the user has an ID before updating
        if (user.id.isNotEmpty()) {
            firestore.collection("users")
                .document(user.id)
                .set(user) // or .update() if you only want to change specific fields
                .await()
        }
    }
}