package com.example.rs_link.data.repository

import com.example.rs_link.data.model.Contact
import com.example.rs_link.data.model.User
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.tasks.await
import javax.inject.Inject

class UserRepositoryImpl @Inject constructor(
    private val auth: FirebaseAuth,
    private val firestore: FirebaseFirestore
) : UserRepository {

    override suspend fun login(email: String, password: String) {
        // Firebase Auth Login
        auth.signInWithEmailAndPassword(email, password).await()
    }
    override suspend fun registerUser(user: User, password: String) {
        // 1. Create Auth User (Email/Password)
        val authResult = auth.createUserWithEmailAndPassword(user.email, password).await()
        val firebaseUser = authResult.user ?: throw Exception("User creation failed")

        // 2. Create the User object with the new Firebase ID
        // (Copy the ID generated by Auth into your User model)
        val newUserWithId = user.copy(id = firebaseUser.uid)

        // 3. Save the Profile Data to Firestore
        firestore.collection("users")
            .document(firebaseUser.uid) // Use the Auth ID as the Document ID
            .set(newUserWithId)
            .await()
    }
    override fun logout() {
        auth.signOut()
    }

    override fun isUserLoggedIn(): Boolean {
        return auth.currentUser != null
    }

    override fun getCurrentUserId(): String? {
        return auth.currentUser?.uid
    }
    override suspend fun getUserProfile(userId: String): User? {
        // Fetch the document from Firestore and convert it to your User object
        return try {
            // Go to "users" collection -> find document with userId -> fetch it
            val snapshot = firestore.collection("users")
                .document(userId)
                .get()
                .await() // Suspends until data is ready

            // Convert the JSON document into your Kotlin 'User' object
            snapshot.toObject(User::class.java)
        } catch (e: Exception) {
            e.printStackTrace()
            null // Return null if network fails
        }
    }

    override suspend fun updateUserProfile(user: User) {
        // Ensure the user has an ID before updating
        if (user.id.isNotEmpty()) {
            firestore.collection("users")
                .document(user.id)
                .set(user) // or .update() if you only want to change specific fields
                .await()
        }
    }
    override suspend fun addEmergencyContact(
        firstName: String,
        lastName: String,
        number: String,
    ) {
        val uid = auth.currentUser?.uid ?: return

        // Create the map with separate fields
        val contact = hashMapOf(
            "firstName" to firstName, // Optional: Store combined for easy searching later
            "lastName" to lastName,
            "number" to number
        )

        firestore.collection("users")
            .document(uid)
            .collection("contacts")
            .add(contact)
            .await()
    }
    override fun getEmergencyContacts(): Flow<List<Contact>> = callbackFlow {
        val uid = auth.currentUser?.uid
        if (uid == null) {
            trySend(emptyList()) // No user, empty list
            close()
            return@callbackFlow
        }

        // Listen to the 'contacts' sub-collection
        val listener = firestore.collection("users")
            .document(uid)
            .collection("contacts")
            .addSnapshotListener { snapshot, error ->
                if (error != null) {
                    close(error)
                    return@addSnapshotListener
                }

                if (snapshot != null) {
                    val contacts = snapshot.documents.mapNotNull { doc ->
                        doc.toObject(Contact::class.java)?.copy(id = doc.id)
                    }
                    trySend(contacts) // Send the new list to ViewModel
                }
            }

        awaitClose { listener.remove() }
    }

    override suspend fun updateEmergencyContact(contact: Contact) {
        val uid = auth.currentUser?.uid ?: return
        firestore.collection("users").document(uid)
            .collection("contacts").document(contact.id)
            .set(contact) // Overwrites with new data
            .await()
    }

    override suspend fun deleteEmergencyContact(contactId: String) {
        val uid = auth.currentUser?.uid ?: return
        firestore.collection("users").document(uid)
            .collection("contacts").document(contactId)
            .delete()
            .await()
    }

    override suspend fun getContactById(contactId: String): Contact? {
        val uid = auth.currentUser?.uid ?: return null
        return firestore.collection("users").document(uid)
            .collection("contacts").document(contactId)
            .get().await()
            .toObject(Contact::class.java)?.copy(id = contactId)
    }

    private val _sensorData = MutableStateFlow("Waiting...")
    override val sensorData = _sensorData.asStateFlow()

    override suspend fun updateSensorData(data: String) {
        _sensorData.value = data
    }

    private val _connectionStatus = MutableStateFlow("Disconnected")
    override val connectionStatus = _connectionStatus.asStateFlow()

    override suspend fun updateConnectionStatus(status: String) {
        _connectionStatus.value = status
    }
    override suspend fun sendEmailVerification() {
        // Sends the standard Firebase "Verify your email" link
        auth.currentUser?.sendEmailVerification()?.await()
    }

    override suspend fun reloadUser() {
        // Crucial: You must reload to get the latest "isEmailVerified" status
        // otherwise it stays false even after they click the link.
        auth.currentUser?.reload()?.await()
    }

    override fun isEmailVerified(): Boolean {
        return auth.currentUser?.isEmailVerified == true
    }
}